# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName("Dialog")
		Dialog.resize(400, 300)
		self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
		self.verticalLayout.setObjectName("verticalLayout")
		self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
		self.stackedWidget.setObjectName("stackedWidget")
		self.page_idle = QtWidgets.QWidget()
		self.page_idle.setObjectName("page_idle")
		self.button_idle = QtWidgets.QPushButton(self.page_idle)
		self.button_idle.setGeometry(QtCore.QRect(-40, -10, 441, 301))
		self.button_idle.setText("")
		self.button_idle.setAutoDefault(True)
		self.button_idle.setFlat(True)
		self.button_idle.setObjectName("button_idle")
		self.label = QtWidgets.QLabel(self.page_idle)
		self.label.setGeometry(QtCore.QRect(46, 25, 291, 211))
		self.label.setScaledContents(False)
		self.label.setAlignment(QtCore.Qt.AlignCenter)
		self.label.setObjectName("label")
		self.label.raise_()
		self.button_idle.raise_()
		self.stackedWidget.addWidget(self.page_idle)
		self.page_app_coupon = QtWidgets.QWidget()
		self.page_app_coupon.setObjectName("page_app_coupon")
		self.button_app = QtWidgets.QPushButton(self.page_app_coupon)
		self.button_app.setGeometry(QtCore.QRect(80, 190, 80, 23))
		self.button_app.setObjectName("button_app")
		self.button_coupon = QtWidgets.QPushButton(self.page_app_coupon)
		self.button_coupon.setGeometry(QtCore.QRect(240, 190, 80, 23))
		self.button_coupon.setObjectName("button_coupon")
		self.stackedWidget.addWidget(self.page_app_coupon)
		self.page_scan_qr = QtWidgets.QWidget()
		self.page_scan_qr.setObjectName("page_scan_qr")
		self.label_7 = QtWidgets.QLabel(self.page_scan_qr)
		self.label_7.setGeometry(QtCore.QRect(170, 130, 57, 16))
		self.label_7.setObjectName("label_7")
		self.stackedWidget.addWidget(self.page_scan_qr)
		self.page_open_door = QtWidgets.QWidget()
		self.page_open_door.setObjectName("page_open_door")
		self.label_2 = QtWidgets.QLabel(self.page_open_door)
		self.label_2.setGeometry(QtCore.QRect(160, 110, 81, 16))
		self.label_2.setObjectName("label_2")
		self.stackedWidget.addWidget(self.page_open_door)
		self.page_insert_object = QtWidgets.QWidget()
		self.page_insert_object.setObjectName("page_insert_object")
		self.label_3 = QtWidgets.QLabel(self.page_insert_object)
		self.label_3.setGeometry(QtCore.QRect(146, 110, 91, 20))
		self.label_3.setObjectName("label_3")
		self.stackedWidget.addWidget(self.page_insert_object)
		self.page_close_door = QtWidgets.QWidget()
		self.page_close_door.setObjectName("page_close_door")
		self.label_4 = QtWidgets.QLabel(self.page_close_door)
		self.label_4.setGeometry(QtCore.QRect(156, 140, 71, 20))
		self.label_4.setObjectName("label_4")
		self.stackedWidget.addWidget(self.page_close_door)
		self.page_processing = QtWidgets.QWidget()
		self.page_processing.setObjectName("page_processing")
		self.label_5 = QtWidgets.QLabel(self.page_processing)
		self.label_5.setGeometry(QtCore.QRect(140, 120, 91, 16))
		self.label_5.setObjectName("label_5")
		self.stackedWidget.addWidget(self.page_processing)
		self.page_full_bin = QtWidgets.QWidget()
		self.page_full_bin.setObjectName("page_full_bin")
		self.label_6 = QtWidgets.QLabel(self.page_full_bin)
		self.label_6.setGeometry(QtCore.QRect(120, 130, 131, 16))
		self.label_6.setObjectName("label_6")
		self.stackedWidget.addWidget(self.page_full_bin)
		self.verticalLayout.addWidget(self.stackedWidget)

		self.retranslateUi(Dialog)
		self.stackedWidget.setCurrentIndex(7)
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
		self.label.setText(_translate("Dialog", "Idle"))
		self.button_app.setText(_translate("Dialog", "App"))
		self.button_coupon.setText(_translate("Dialog", "Coupon"))
		self.label_7.setText(_translate("Dialog", "Scann QR"))
		self.label_2.setText(_translate("Dialog", "Open door"))
		self.label_3.setText(_translate("Dialog", "Insert Object"))
		self.label_4.setText(_translate("Dialog", "Close door"))
		self.label_5.setText(_translate("Dialog", "Processing"))
		self.label_6.setText(_translate("Dialog", "Recycling bin full"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	Dialog = QtWidgets.QDialog()
	ui = Ui_Dialog()
	ui.setupUi(Dialog)
	Dialog.show()
	sys.exit(app.exec_())
